#pragma once

// From glfw3.h
#define VOXEL_MOUSE_BUTTON_1 0
#define VOXEL_MOUSE_BUTTON_2 1
#define VOXEL_MOUSE_BUTTON_3 2
#define VOXEL_MOUSE_BUTTON_4 3
#define VOXEL_MOUSE_BUTTON_5 4
#define VOXEL_MOUSE_BUTTON_6 5
#define VOXEL_MOUSE_BUTTON_7 6
#define VOXEL_MOUSE_BUTTON_8 7
#define VOXEL_MOUSE_BUTTON_LAST VOXEL_MOUSE_BUTTON_8
#define VOXEL_MOUSE_BUTTON_LEFT VOXEL_MOUSE_BUTTON_1
#define VOXEL_MOUSE_BUTTON_RIGHT VOXEL_MOUSE_BUTTON_2
#define VOXEL_MOUSE_BUTTON_MIDDLE VOXEL_MOUSE_BUTTON_3
